server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3306/school_management?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?? Hibernate t? sinh b?ng t? Entity
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  signerKey: "32ByteLongSecretSignerKeyForSchoolManagementSystem2026!!!"
  validDuration: 86400 # 24 hours
  refreshableDuration: 2592000 # 30 days

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:bl3xlplj}
  api_key: ${CLOUDINARY_API_KEY:826916337714229}
  api_secret: ${CLOUDINARY_API_SECRET:R_gVqkAxZvjxhd1tBC4ju5wg5f8}